version: '3.8'

services:
  app:
    image: payman
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:3000"
    volumes:
      - ./:/usr/src/app
      - ./data:/usr/src/app/data
    environment:
      - NODE_ENV=production
    restart: unless-stopped
